export const worldMemoryActionCatalog = {
  audit: { label: "Audit", riskLevel: "low" },
  harness: { label: "하네스 검증", riskLevel: "low" },
  list: { label: "최근 엔트리 조회", riskLevel: "low" },
  states: { label: "상태 스냅샷 조회", riskLevel: "low" },
  taxonomy: { label: "Taxonomy 조회", riskLevel: "low" },
  taxonomyRefresh: { label: "Taxonomy 재색인", riskLevel: "medium" },
  cleanupDryRun: { label: "Cleanup dry-run", riskLevel: "low" },
  briefStoryBackfill: { label: "Brief story backfill", riskLevel: "medium" },
  storyLink: { label: "스토리 관계 기록", riskLevel: "medium" },
  storyMap: { label: "스토리 맵 조회", riskLevel: "low" },
  storyFamilyReview: { label: "스토리 패밀리 리뷰", riskLevel: "low" },
  stateAdd: { label: "Watch state 기록", riskLevel: "medium" },
  semanticSearch: { label: "의미 검색", riskLevel: "low" },
  stateSync: { label: "파생 상태 동기화", riskLevel: "medium" },
  refreshReport: { label: "보고서/변경 제안 갱신", riskLevel: "low" },
  embedStatus: { label: "임베딩 커버리지", riskLevel: "low" },
  report: { label: "월드 메모리 보고서", riskLevel: "low" },
  collectNow: { label: "수동 수집", riskLevel: "network" },
  pause: { label: "다음 수집 6시간 연기", riskLevel: "low" },
};
